name: Performance Tests

on:
  push:
  pull_request:

jobs:
  build:
    env:
      # We use these variables to convert between tox and GHA version literals
      py35: 3.5
      py36: 3.6
      py37: 3.7
      py38: 3.8
      pypy3: pypy3
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package-group: ["core" ]
        python-version: [ py35 ]
    steps:
      - name: Checkout Repo @ SHA - ${{ github.sha }}
        uses: actions/checkout@v2
      - name: Set up Python ${{ env[matrix.python-version] }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env[matrix.python-version] }}
      - name: Install tox
        run: pip install -U tox-factor
      - name: Cache tox environment
        # Preserves .tox directory between runs for faster installs
        uses: actions/cache@v2
        with:
          path: .tox
          key: tox-cache-${{ hashFiles('tox.ini') }}
      - name: run tox
        run: tox -f ${{ matrix.package-group }} -- --benchmark-json=${{ matrix.package-group }}-benchmark.json
      - name: Find and merge benchmarks
        run: jq -s '.[0].benchmarks = ([.[].benchmarks] | add) | if .[0].benchmarks == null then null else .[0] end' */tests/*${{ matrix.package-group }}*.json > output.json
      - name: Push benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: OpenTelemetry Python Benchmarks - Python ${{ env[matrix.python-version ]}} - ${{ matrix.package-group }}
          tool: pytest
          output-file-path: output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Alert with a commit comment on possible performance regression
          alert-threshold: 200%
          comment-always: true
          fail-on-alert: true
          alert-comment-cc-users: '@${{ github.event.issue.user.login }}'
          # Make a commit on `gh-pages` with benchmarks from previous step
          auto-push: ${{ github.ref == 'refs/heads/mainline' }}
          benchmark-data-dir-path: benchmarks
